### ISSUE TITLE
開発環境の作成

### ISSUE THREAD

**Issue by naoki0531** [full-party/CrossUp#1]
- [x] サーバーサイド
- [x] フロントサイド

**Comment by naoki0531** [comment]
dockerはアプリケーション単位で作成
・WEB
・mysql
・apache

mysqlとapacheはdockerHubで公開されているので、簡単な記述で作成できます

docker for macとdocker-composeで作成

dockerFileが必要なのはwebだけで、docker-composeでdockerhubから直接作成可能

**Comment by naoki0531** [comment]
サーバーサイドは一旦完了
今後必要なものが出た場合はチケットを随時作成する

フロントがOKだったら閉じちゃいましょう

**Comment by tiwuofficial** [comment]
フロントはララベルの機能使うため、特に構築する必要はなし。
クローズします
