### ISSUE TITLE
【デザイン】【WF】コンボ一覧画面

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#10]
## コンボ一覧画面のデザイン

#8 に紐付く

### UI、UX、この画面で伝えたいこと

この画面のメインは始動フィルタをして、一番最適なコンボを探す導線
重要なのは始動とダメージ量とスタン値と必殺技使用量である。

コンボを見つけやすい、ほしいコンボにたどり着きやすいUIにする必要がある

右下に検索ボタンを常に表示させる（一番重要）
クリックしたらフィルタとソートができる検索画面が表示される（画面遷移なし）

ちなみにコンボは50ほど登録する

登録は右上の＋アイコンにする（2番め）

コンボの内容はそこまで重要ではない
また、キャラ名はアイコンがあれば一覧に出すほどの情報でなはい

- ヘッダーがある（ロゴとID）
    - なくても良い気はするがあったほうがいいのか？
    - 合った場合追従はさせる必要ない？
    - サイドメニューを置く想定だがスクロールしてサイドメニュー開く需要はあるのか？
    - サイドメニューでゲーム、キャラ、始動の絞り込みをさせる場合追従の方がいいか？

- できるだけ画面内に多くのコンボ一覧を見せる
    - 理由としてはコンボを見るのがメインのサイトなのでそれ以外はノイズになる可能性がある

- ゲーム毎に自分の登録したコンボ一覧が見れる（一覧に混ざることはない）
    - そんなに頻繁にゲームを切り替えることはあるのか？
    - 上部に設置するタブのようにそんなに重要か？
    - 画面内に切り替える機能を表示しなくてもいいのでは？（サイドメニューで隠しておくとか）

- キャラで絞り込みができる
    - キャラの数は膨大のためセレクトボックスで選ぶ想定
    - セレクトボックスはセレクトボックスタップ→選ぶ→閉じるという流れのためアクション数が多い
    - またキャラ名のためビジュアル的に弱い気がする（キャラなのでキャラの画像を見て選べたほうが良い気がする）
        - セレクトボックス以外を考えたい 
        - サイドメニューにキャラ絞り込みボタンを設置しポップアップでキャラ一覧を出す？
    - 始動の絞り込みとキャラの絞り込みではどちらのほうが良く使う機能なのか？

- 始動で絞り込みができる
    - コンボの数も膨大のためセレクトボックスで選ぶ想定
        - キャラと違ってテキストで大丈夫
    - しかし、キャラより膨大のため単純にセレクトボックスだとどこに目的の始動があるか見つけづらそう
    - テーブルみたいに横4列縦X列にしたほうが見つけやすいはず
    - サイドメニューに始動絞り込みボタンを設置しポップアップで始動一覧を出す？

- コンボの一覧が見れ、詳細画面に遷移ができる
    - キャラのアイコン
    - コンボ（途中はいらない）
        - 始まりと終わりの2つ
    - ダメージ量
    - スタン値
    - 必殺技ゲージ使用量

コンボ修正やコンボの削除は今回はいれない

### 備考

食べログの一覧は条件変更ボタンが上部追従ヘッダーにある
コンボ一覧も同じUIの方がいい？

その場合上部追従ヘッダーにゲーム切り替えボタン、キャラ絞り込みボタン、始動絞り込みボタンを置く？

ただ、今後絞り込みは増えるためそれぞれボタンを置くと収まらない

主要の絞り込みはボタンにして、その他は詳細絞り込みボタンにして絞り込みさせる？

## 超ざっくりWF

<img src="https://cloud.githubusercontent.com/assets/13449349/25232809/a75f9984-2617-11e7-8c5f-b869b467b940.jpg" width="320px">

**Comment by tiwuofficial** [comment]
カード型にするほどコンボ自体を魅せたいわけではなく、コンボ自体の比較のはずのため下記のようなリストにする。

また、検索がかなり重要なので右下のボタンにする

ゲーム切り替え、ID、コンボ追加はそこまで重要ではないと推測するので右上のハンバーガーメニューで隠す

<img src="https://cloud.githubusercontent.com/assets/13449349/25778716/99ac45da-3341-11e7-803f-a056514ec6e0.png" width="320px">

**Comment by naoki0531** [comment]
おお　カックイー！！！

＞写真がキャラの写真になる？とキャラの絞り込みした時全部一緒になるし、
たしかにそうですね、絞り込んだら全部同じキャラの顔になるし
そんな目立たなくてもいいので小さいやつでいいですね

＞ゲーム切り替え、ID、コンボ追加はそこまで重要ではないと推測するので右上のハンバーガーメニューで隠す
これも同意です。
極限まで検索と比較に特化した画面にしましょう

**Comment by tiwuofficial** [comment]
## サイドメニュー

- メアド
- コンボ追加画面への遷移
- ゲーム切り替えボタン
- ログアウト
- 退会

ログアウトと退会はミニマムとは言え必須と考える

ログアウトは押したらトップに戻るが

退会は退会画面（新規）に遷移し、注意書きを表示し退会させる必要があると考える

ゲーム切り替えはポップアップが開きゲームを選択させる

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32051366-4ce76a1a-ba8f-11e7-8625-d7a550211494.png)

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32052099-1aa59b96-ba92-11e7-871c-d9239bf2d64f.jpg)

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32052343-f0ba0e10-ba92-11e7-9f12-2befdca4603b.jpg)

**Comment by tiwuofficial** [comment]
![desktop](https://user-images.githubusercontent.com/13449349/32169174-bdf5a728-bdb2-11e7-838a-29404aff13ee.png)

**Comment by tiwuofficial** [comment]
WFとしては完成

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32493886-df1e37d4-c402-11e7-8c3a-9ddec378b319.png)

カセット調整
