### ISSUE TITLE
【デザイン】コンボ詳細画面

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#11]
## コンボ詳細画面のデザイン

#8 に紐付く

### UI、UX、この画面で伝えたいこと

一覧で始動やダメージ量、スタン値、必殺技使用量は見えるので詳細で一番知りたいのは

メモとコンボの内容

画面上部にキャラアイコン、キャラ名、ダメージ量、スタン値、必殺技使用量は表示し

画面中央にコンボを、その下にメモを表示する

すべてFVで表示させたい

ヘッダーには、アイコン、登録ボタン

## 超ざっくりWF

<img src="https://cloud.githubusercontent.com/assets/13449349/25339603/423ce15e-293e-11e7-9524-4b5d38fed591.jpg" width="320px">

**Comment by tiwuofficial** [comment]
<img src="https://cloud.githubusercontent.com/assets/13449349/25779180/4566f2a2-334d-11e7-9355-ff88e97bfb09.png" width="320px">

**Comment by naoki0531** [comment]
あ、スタン値の下にゲージ使用量の追加をお願いします！
編集ボタンってどうするって話しましたっけ？

**Comment by tiwuofficial** [comment]
ゲージ使用量の追加承知です。

編集と削除はどうしましょう・・・？

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32170187-fd64edd4-bdb6-11e7-8e14-095851a9f3dd.png)

**Comment by tiwuofficial** [comment]
![desktop](https://user-images.githubusercontent.com/13449349/32170407-c17a0c2c-bdb7-11e7-835e-5a0f510625cd.png)

**Comment by tiwuofficial** [comment]
WF完成
