### ISSUE TITLE
【API】ストファイの技を全て登録する

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#111]
現在MovesTableSeeder.phpに少ししか技がないので、他の全キャラクターの技を用意する。

## 案1

全てMovesTableSeeder.phpに書く

## 案2

外部csvファイルなどを作成し、MovesTableSeeder.phpで読み込む。

**Comment by naoki0531** [comment]
技についてはおそらく共通化できる点が少ない
キャラによって5Pでも、ダメージやスタン値が固有になっているため

なので、Seederでコードを書いたとしても、定数ファイル参照地獄になると思われるので
技はcsv登録にしましょう

**Comment by tiwuofficial** [comment]
csv了解でっす！
