### ISSUE TITLE
【デザイン】コンボ入力画面 

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#13]
## コンボ入力画面のデザイン

#8 に紐付く

### UI、UX、この画面で伝えたいこと

コンボ入力をいかにめんどくさくなくできるかがUI、UXでがんばるところ

必須なのはキャラとコンボ

メモやダメージ量やスタン値、必殺技使用量は必須ではない

コンボはキャラによって違うのでキャラを選んだら非同期に変える必要がある
→スムーズに切り替えたい

- 入力フォーム
    - キャラの選択
        - ポップアップで表示させる？
        - セレクトボックスはつらそう
    - コンボ入力
        - 技を全て表示させておく
        - タップしてコンボを入力する
        - 一括削除、一つだけ削除ボタンを設置
    - メモ入力（フリーテキスト）
    - 合計ダメージ値入力（数値）
    - 合計スタン値入力（数値）
    - 必殺技使用量（数値）

- コンボ登録ボタン
    - 一番下よりは常に右下に表示させる？
    - 微妙にマテリアルデザインで統一されてなくてキモい？

## 超ざっくりWF

<img src="https://cloud.githubusercontent.com/assets/13449349/25340239/0e844634-2940-11e7-99ce-69f93194337e.jpg" width="320px">

**Comment by tiwuofficial** [comment]
<img src="https://cloud.githubusercontent.com/assets/13449349/25779359/f3c0e22e-3350-11e7-86c8-ba8dd8aabd4b.png" width="320px">

**Comment by naoki0531** [comment]
詳細と同じくゲージ使用量の追加をお願いします。
２Pや５Pって書いてあるところが、キャラやゲームによって数が変動するので
横何個並べるかとか考えないと下に伸びていっちゃいそうですね・・
でも４個ぐらいが限界か

**Comment by tiwuofficial** [comment]
ゲージ使用量承知いたしました。追加します。

技？のところは無理やりボタン内に入れるか（2行にしたり）ある程度可変で自動で敷き詰めるようにするか考えてみます。

一番長い技？でどれくらいの文字数になるか調査します。

**Comment by tiwuofficial** [comment]
入力した技を消せないので、消すボタンを追加する

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32326551-96ae042e-c016-11e7-9ff4-9a3366d1213e.png)

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32326720-3a4fe85e-c017-11e7-96f2-9be6d7a730d8.png)

**Comment by tiwuofficial** [comment]
![desktop](https://user-images.githubusercontent.com/13449349/32327888-70e96f8a-c01b-11e7-8ac9-3b4e6391d9b1.png)

**Comment by tiwuofficial** [comment]
WF完成

**Comment by tiwuofficial** [comment]
技の削除と、全削除ボタンを忘れたので再度OPEN

**Comment by tiwuofficial** [comment]
![iphone 8](https://user-images.githubusercontent.com/13449349/32328183-8764e928-c01c-11e7-940c-ab91d7890a69.png)

**Comment by tiwuofficial** [comment]
![desktop](https://user-images.githubusercontent.com/13449349/32328225-a995661c-c01c-11e7-9653-e787e0d9159b.png)

**Comment by tiwuofficial** [comment]
削除を追加したので再度クローズ
