### ISSUE TITLE
リリース手順の作成

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#24]
# リリース手順の作成

どうやってリリースしましょう？

**Comment by naoki0531** [comment]
基本的にはmaster mergeでherokuの自動デプロイでOK
ただ、マスタデータに変更が入った場合に現在は運用が必要。
そのため、その場合の手順書のみ作成が必要

**Comment by naoki0531** [comment]
https://github.com/full-party/CrossUp/wiki/%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E6%89%8B%E9%A0%86

wikiにリリース手順を追加。
自動化すべきではあるが、現状はそこまで頻度が高いものでもないので後回し。
別チケきっているので、手順に問題なければクローズしてください！

**Comment by tiwuofficial** [comment]
herokuのコマンドのインストール手順も書いてあると助かります。
また、herokuのログインコマンドってIDとか必要ですか？

**Comment by naoki0531** [comment]
手順を更新しました！
DBマイグレーションが実行できるか試してみてください。
試しても本番影響はないのでOKです

**Comment by naoki0531** [comment]
完了したのでクローズ
