### ISSUE TITLE
本番環境の作成

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#25]
# 本番環境の作成

ドメイン取得したり？
herokuの設定したり？

**Comment by naoki0531** [comment]
- [ ] herokuの設定
- [ ] 本番環境に伴うファイル追加など
- [ ] 本番用のmigration

**Comment by naoki0531** [comment]
・Seederについて
マスターデータについてはidのオートインクリメントを外したい
理由として、オートインクリメントなど既存のDB状態によって値が変化するものをマスターデータの固定値にしてしまうと以下のような症状が発生する

```
オートインクリメントでスト5のIDが3に。
しかしcharacterテーブルのseederではリュウのgameIDが2に設定されているため不整合
```

・他のユニーク値があればそれを検索してスト５のIDを取得して、リュウに設定するなどできるが
現状ではgamesテーブルのnameしかユニーク値がない

今後新キャラの追加などでマスターデータにオートインクリメントが発生した場合なども
考慮する必要が出てしまう

**Comment by naoki0531** [comment]
解決策として、**マスターデータ**に関してはidのオートインクリメントを外し
idもDB登録時に指定する。

コンボやユーザーなどマスターデータとして必要ないものはオートインクリメントをつけたままにする

**Comment by naoki0531** [comment]
本番自動デプロイ環境の設定完了
