### ISSUE TITLE
【API】ユーザー削除

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#49]
IDを送信して削除できる

**Comment by naoki0531** [comment]
delete
api/users/

**Comment by naoki0531** [comment]
これって今回のスコープにいるかな？？
そもそも削除する機能がないから、優先度低でもいいかもしれないですね

**Comment by tiwuofficial** [comment]
ユーザー登録できるけど、削除できないのはサービスとして問題あるかなと思ったので必要と思ってます！
