### ISSUE TITLE
【デザイン実装】【SP】【コンボ一覧画面】コンボカセット実装

### ISSUE THREAD

**Issue by naoki0531** [full-party/CrossUp#5]
https://github.com/full-party/CrossUp/issues/10

上記コンボ一覧画面のデザイン実装

**Comment by tiwuofficial** [comment]
SPのコンボ一覧画面のコンボカセットのデザイン実装。

**Comment by tiwuofficial** [comment]
https://codesandbox.io/s/o29j95wx9

上記公式サンプルを参考にする
