### ISSUE TITLE
【デザイン】トップ画面

### ISSUE THREAD

**Issue by tiwuofficial** [full-party/CrossUp#9]
## トップ画面のデザイン

#8 に紐付く

### どういう人がどういうシチュエーションでこのトップ画面にくるか

- 検索してくる人
- 何かの記事で紹介され、そこからくる人

基本的には格ゲーやってた、やってる人がトップ画面にくるはず
→メモを取るという文化が浸透しているのか？

※既にこのサイトを使ってる人はこの画面に来ることはないと考える
　→既にログインしているため再び使うときはコンボ一覧画面を最初に見ると考える

### 登録フローのイメージ

登録フォームを埋める
↓
メールがくる
↓
メールのリンクにアクセス
↓
トップ画面にアクセスし、登録完了を伝える。
登録フォームではなく、ログインフォームを表示させる。
※リンクは一覧のほうがいいか？

### UI、UX、この画面で伝えたいこと

- FVは新規登録フォームを出し、すぐ登録できるようにする
    - 登録済みの人はこの画面にくることはあまりないはず
    - 新規登録してログインフォームを出してログインさせる

- 格ゲーのメモを取るサイトということを伝える
    - どの範囲の人までに伝わるようにするかはヒアリング中

- 格ゲーのメモをとるのに便利ということを伝える
    - どの点が使いやすいかリストアップする必要がある
    - 現状はどこが使いづらいか。それをどう解決するか。

- どの格ゲーのメモが取れるか伝える（スト2、ギルティ）
    - ゲームの画像って使って良いのか？
    - テキストだけにするか？

- FVで格ゲーやる人が見ても格ゲーのコンボのメモをするサイトとわかること
    - 格ゲーやらない人が見た場合はどうするか？
    - そもそも格ゲーやらない人は対象にするか？
    - 少しやっただけの人はそもそもメモをとるという発想がないはず
        - 上記のような人が見た場合

- 誰が実装したか
    - いらない？

- SNSとか？
    - ツイッターとか必要？

- コピーライト

## 超ざっくりWF

<img src="https://cloud.githubusercontent.com/assets/13449349/25231429/ceced908-2612-11e7-9328-21a031367a60.jpg" width="320px">

<img src="https://cloud.githubusercontent.com/assets/13449349/25231508/145de22a-2613-11e7-91fc-11b1f99a3bf9.jpg" width="320px">

<img src="https://cloud.githubusercontent.com/assets/13449349/25231536/2acecea2-2613-11e7-8a90-f0cb2fbf53ec.png" width="320px">

**Comment by tiwuofficial** [comment]
### 追記

格ゲーやってない、ちょっとしかやってない人は無視

一番伝えたいのは、このサービスは格ゲーのメモを取るのに便利ということ

**Comment by tiwuofficial** [comment]
これをパクる

http://designstub.com/demos/rooky/

**Comment by tiwuofficial** [comment]
![desktop](https://user-images.githubusercontent.com/13449349/31942180-71f4fea8-b8ff-11e7-8653-d70624bff20c.png)

**Comment by aw-n-maruyama** [comment]
いいですね！！！！！！

**Comment by tiwuofficial** [comment]
![desktop](https://user-images.githubusercontent.com/13449349/31998438-d97234d0-b9ca-11e7-8c27-7f458cb62a82.png)

![iphone 7](https://user-images.githubusercontent.com/13449349/31998444-de59564a-b9ca-11e7-9362-afbb3042dca8.png)

**Comment by tiwuofficial** [comment]
WFとしては一旦完了。
文書などは適当で別Issueでやる。
